#!/bin/bash

# Para obter lista de grupos de indicadores de performance:
#      likwid-perfctr -a

# Para obter topologia dos processadores
#      likwid-topology -c -g

data="data.txt"
report="report.txt"
n=(512 1024 2048)
titles=("Transposta" "TranspostaUJ" "TranspostaBlocking" "Mult" "MultUJ" "MultBlocking")
files=("L2CACHE-512.txt" "L3-512.txt" "L2CACHE-1024.txt" "L3-1024.txt" "L2CACHE-2048.txt" "L3-2048.txt")

make likwid

for n in ${n[@]}
do
	likwid-perfctr -C 0 -g L2CACHE -m ./matmult -n $n > L2CACHE-$n.txt
	likwid-perfctr -C 0 -g L3 -m ./matmult -n $n > L3-$n.txt
done

for file in ${files[@]}
do
	filename=$(echo $file | cut -d"." -f1)
	printf "\n$filename\n"
	tmt=($(grep "Tmt" $file | awk -F" " '{print $3}'))
	tmmm=($(grep "Tmmm" $file | awk -F" " '{print $3}'))
	echo "Metodo" ${titles[@]}
	echo "Tempo" ${tmt[@]} ${tmmm[@]}
	filetype=$(grep -c "L3" $file)
	if [ $filetype -gt 0 ]
	then		
		bandwidth=($(grep "L3 bandwidth" $file | awk -F" " '{print $6}'))
		echo "Bandwidth" ${bandwidth[@]}
	else
		miss=($(grep "L2 miss ratio" $file | awk -F" " '{print $6}'))
		echo "MissRatio" ${miss[@]}
	fi
done > $data

column -e -s " " -t $data > $report

rm $data ${files[@]}

make purge
